config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    resources :users
    resources :items


    resources :users, only: [:show] do
      resources :personal_items, only: [:new, :show, :index, :edit, :destroy, :update]
    end

    resources :personal_items

  get "/signup" => "users#new", as: "signup"
  get "/login" => "sessions#new", as: "login"
  post "/login" => "sessions#create"
  # as only for get not delete or post
  delete "/logout" => "sessions#destroy"

  root 'sessions#new'

  # Routes for Google authentication
  get 'auth/:provider/callback', to: 'sessions#googleAuth'
  get 'auth/failure', to: redirect('/')

  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
	# has_many :categories
	has_many :personal_items
	has_many :users, through: :personal_items
	
	validates_associated :personal_items

end

app/models/personal_item.rb
class PersonalItem < ApplicationRecord
	belongs_to :user
	belongs_to :item

	validates :user_id, presence: true

  scope :last_updated, -> { order("updated_at desc")}	
  scope :last_acquired, -> { order("last_acquired desc")}
  scope :limitvalue, -> { order("updated_at desc").limit(3)}	

end

app/models/user.rb
class User < ApplicationRecord
	
	has_many :personal_items
	has_many :items, through: :personal_items
    validates :username, uniqueness: true
    # validates_associated :personal_items error 
    validates :password, presence: true, on: :create
	has_secure_password


	def self.g_random_code(number)
        array = Array('A'..'Z') + Array('a'..'z')
        Array.new(number) { array.sample }.join
    end      

    def self.from_omniauth(auth)
        # Creates a new user only if it doesn't exist
        where(email: auth.info.email).first_or_initialize do |user|

            user.email = auth.info.email
            user.username = auth.info.name + rand(1..1000).to_s
            user.name = auth.info.name
            password = self.g_random_code(19)
            user.password = password

        end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	helper_method :logged_in?
	helper_method :current_user
	helper_method :authorize

	private
	
	def logged_in?
		!!current_user
		# double bang keep track of who is logged in
	end

	def current_user
		User.find_by(id: session[:user_id])
	end

	def log_in(user)
		session[:user_id] = user.id
	end

	def authorize
        if params[:user_id].to_i != current_user.id
        flash[:danger] = "You are not authorized to see this page."
        redirect_to login_path
        end
    end


	def authenticate
		if !logged_in?
			redirect_to login_path
		end
	end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	def show
    	@item = Item.find(params[:id])
  	end
end

app/controllers/personal_items_controller.rb
class PersonalItemsController < ApplicationController
	before_action :authenticate
  before_action :get_personal_item, only: [:edit, :update, :show, :destroy]

  def new
    @personal_item = PersonalItem.new
  end

	def index
    authenticate
    authorize
		# @personal_item = PersonalItem.all
    if params[:user_id]
      # raise params.inspect
      # binding.pry
      @personal_items = User.find(params[:user_id]).personal_items
      if !params[:limit]
        @personal_items = @personal_items.last_updated
      else
        @personal_items = @personal_items.limitvalue
      end
      # last_updated scope from model
    else
      @personal_items = PersonalItem.all
	end
end

  def create
    # @item = Item.find(params[:item_id])
    # @personal_item.user = current_user
    # @personal_item.item = @item
    @personal_item = PersonalItem.new(personal_item_params)
    if @personal_item.save
      redirect_to user_personal_items_path(current_user) # not personal_items_path
    else
      render :new
    end
  end
	  
	  def show
      redirect_to user_personal_items_path(current_user) # not personal_items_path
      # redirect_to personal_items_path
      # show e.g. http://localhost:3000/personal_items/1/ redirects to the main index nested route
  	end

  	def edit
      authenticate
      # authorize doesn't work
  	end

    def destroy
      authenticate
      @personal_item.destroy
      redirect_to user_personal_items_path(current_user)
    end

    def update
      authenticate
      @personal_item.update(personal_item_params)
      redirect_to user_personal_items_path(current_user)
      # patch
    end

  private

  def personal_item_params
    params.require(:personal_item).permit(:note, :date_acquired, :status, :item_id, :user_id) # item_id:[],
  end

  def get_personal_item
    @personal_item = PersonalItem.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		@user = User.find_by(username: params[:username]) #must make sure using find_by is unique
		if @user && @user.authenticate(params[:password])
			flash[:success] = "Hello #{@user.name}"
			log_in(@user)
			redirect_to @user
		else
			flash[:danger] = "You entered the wrong credentials."
			redirect_to login_path

		end

	end


	def destroy
		session.clear
		redirect_to login_path
	end



	    def googleAuth
        # Get access tokens from the google server
        access_token = request.env["omniauth.auth"]
        @user = User.from_omniauth(access_token)
        # log_in(@user)
        # Access_token is used to authenticate request made from the rails application to the google server
        @user.google_token = access_token.credentials.token
        # Refresh_token to request new access_token
        # Note: Refresh_token is only sent once during the first request
        refresh_token = access_token.credentials.refresh_token
        @user.google_refresh_token = refresh_token if refresh_token.present?
       
        if @user.save
            log_in(@user)
            flash[:success] = "Welcome #{@user.name}!"
            redirect_to user_path(@user)
        else
            flash[:danger] = "Login credentials were incorrect, please try again."
            redirect_to login_path
        end
    end



    

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def index
    authenticate
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      
      redirect_to @user # /uesrs/#{@user.id}
      # same as redirect_to user_path(@user) or link_to @user.name, @user
    else
      render :new
    end
  end

    def show
      authenticate
      @user = User.find(params[:id])
    end

  private

  def user_params
    params.require(:user).permit(:username, :name, :email, :password)
  end
  # clean up TODO
  # if nested forms :personal_items_attributes => [:note, :date_acquired, :status, :item_id, :user_id], :items_attributes => [:name, :brand, :geartype]
end

app/helpers/application_helper.rb
module ApplicationHelper
	def navbar
		if logged_in? #helper method in appcontroller decide what layout to render
			render "layouts/logged_in_navbar"
		else
			render "layouts/logged_out_navbar"
		end
	end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/personal_items_helper.rb
module PersonalItemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_item.html.erb
<%= link_to item.name, item_path(item) %>

app/views/items/index.html.erb
<h4>All Catalog Items: </h4>

<% Item.all.each do |item| %>

<%= render partial: "item", locals: {item: item} %>

<br>
<% end %>

app/views/items/show.html.erb
<h4>Specs for <%= @item.name %></h4>

<div>
	<h5>Item info sheet</h5>
Name: <%= @item.name %><br>
Brand: <%= @item.brand %><br>
Gear Type: <%= @item.geartype %><br>
</div>

app/views/layouts/_logged_in_navbar.html.erb
<%= link_to "User Community", users_path %>
<%= link_to "View Your Personal Inventory", user_personal_items_path(current_user) %>
<%= link_to "Add Personal Item", new_personal_item_path %>
<%= link_to "View Catalog Items", items_path %>
<%= button_to "Log Out", "/logout", method: :delete %>

app/views/layouts/_logged_out_navbar.html.erb
<!-- link_to "Log In", login_path -->
<h1>Climbing Gear Inventory</h1>
<%= link_to "Signup", signup_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClimbingGear</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>

      <% flash.each do |k, v| %>
       <div class="<%= k %>"><%= v %></div>
        <% end %>

      <%= navbar %>
    </header>
    <%= yield %>
  </body>
</html>

app/views/personal_items/_form.html.erb
<!-- personal_item local variable instead of @personal_item -->
<!--  render 'form', personal_item: PersonalItem.new -->

<h1>ADD A PERSONAL ITEM</h1>

<%= form_with model: personal_item, local: true do |f| %>

  <%= f.label :note %>
  <%= f.text_area :note %>
  <br/><br/>

  <%= f.label :date_acquired %>
  <%= f.date_field :date_acquired %>
  <br/><br/>

  <%= f.label :status %>
  <%= f.text_field :status %>
  <br/><br/>

  <%= f.label :item %><br/>
  <%= f.collection_radio_buttons(:item_id, Item.all, :id, :name) do |b| %> 
  <%= b.radio_button %> 
  <%= b.label do %> 
   <%=  b.object.name + " - " + b.object.brand %><br/>
  <% end %> 
  <% end %> 


  <!-- f.collection_select -->


  <br/>

  <%= f.hidden_field :user_id, value: current_user.id %>

  <br/>

  <%= f.submit 'Add' %>

<% end %>

app/views/personal_items/_personal_item.html.erb
<div>
<h3><%= personal_item.item.name%></h3>
Brand: <%= personal_item.item.brand %>
<br/>
Date acquired: <%= personal_item.date_acquired %>
<br/>
Status: <%= personal_item.status %>
<br/>
Notes: <%= personal_item.note %>
<!-- TEST:  personal_item.user.name -->
<!-- link_to personal_item.note, personal_item_path(personal_item) -->
</div>

<!-- non authorize link_to "Edit", edit_personal_item_path(personal_item) -->
<%= link_to "Edit", edit_user_personal_item_path(current_user, personal_item) %>
<%= link_to "Delete", personal_item, method: :delete, data: { confirm: "Do you really want to remove this item?" } %>

app/views/personal_items/edit.html.erb
<%= render partial: "form", locals: {personal_item: @personal_item}  %>
<!-- render "form", personal_item: @personal_item -->
<!-- @personal_item comes from controller will go into local variable personal_item into partial -->

app/views/personal_items/index.html.erb
<h4>Your Inventory: </h4>
<%= button_to "Limit 3", user_personal_items_path(current_user), method: :get, params: {limit: 3}%>


<% @personal_items.each do |personal_item| %>

<%= render partial: "personal_item", locals: {personal_item: personal_item} %>

<br>

<% end %>

app/views/personal_items/new.html.erb
<%= render partial: "form", locals: {personal_item: @personal_item}  %>


<!-- render :form, personal_item: @personal_item  -->
<!-- render partial: "personal_item", locals: {personal_item: personal_item} index.html.erb doesn't need the @personal_item? -->

app/views/personal_items/show.html.erb
<!-- redirects to index -->

app/views/users/_user.html.erb
<%= link_to user.name, user_path(user) %>

app/views/users/index.html.erb
<h4>All Users: </h4>

<% User.all.each do |user| %>

<%= render partial: "user", locals: {user: user} %>

<br>
<% end %>

app/views/users/new.html.erb
<h1>SIGNUP</h1>

<%= form_with model: @user, local: true do |f| %>

  <%= f.label :username %>
  <%= f.text_field :username %>
  <br/>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <br/>

  <%= f.label :email %>
  <%= f.email_field :email %>
  <br/>

  <%= f.label :password %>
  <%= f.password_field :password %>
  <br/>

  <%= f.submit 'Signup' %>


  <% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |msg| %>
        <p><%= msg %></p>
    <% end %>
    <% end %>
    <!-- raise password errors -->

<% end %>

app/views/users/show.html.erb
<h4>Profile for <%= @user.name %></h4>

<div>
	<h5>Profile info</h5>
<%= @user.username %><br>
<%= @user.name %><br>
<%= @user.email %><br>
</div>